# Indico que voy a usar Nodejs
language: node_js
# Indico que voy a usar docker para que se instale
services:
    - docker
# Antes de instalar, descargo el contenedor
before_install:
    - docker pull javizzyv/videogametracker
# Ejecuto el contenedor
script:
    - docker run -t -v /test javizzyv/videogametracker