[build]
  publish = "." # Indico donde se va a publicar
  functions = "/netlify"  # Indico donde están las funciones

[[redirects]]
  from = "/index" # Redirijo desde index
  to = "/.netlify/functions/index"  # a la función que he creado
  status = 200  # Código de que todo ha ido bien